name:Perform Bloodhound Scans
on: [push]
jobs:
  Perform-Bloodhound-Scans:
    runs-on: ubuntu-latest
    container: securestackau/bloodhound-cli:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - name: perform-secret-scan
        shell: bash
        env:
          BH_APP_ID: ${{ secrets.BH_APP_ID }}
          BH_API_KEY: ${{ secrets.BH_API_KEY }}
          BH_SEVERITY: ${{ secrets.BH_SEVERITY }}
        run:
          bloodhound-cli code -s -a $BH_APP_ID

